site_name: havana
repo_url: https://github.com/vhvictorhugo/HAVANA-2.0
site_url: https://vhvictorhugo.github.io/havana
site_description: This is a repository for registry the advanced of including some region embeddings into HAVANA, a graph neural network responsable to classifier semantically points of interests.
site_author: Victor Hugo Santos
edit_uri: edit/main/docs/
repo_name: vhvictorhugo/HAVANA-2.0
copyright: Maintained by <a href="https://vhvictorhugo.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vhvictorhugo/HAVANA-2.0
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/havana

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
